# Generated by Django 6.0.3 on 2026-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('above', 'Price Goes Above'), ('below', 'Price Goes Below'), ('equal', 'Price Equals Target'), ('between', 'Price Between Range')], default='above', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
