# Generated by Django 6.0.3 on 2026-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stockalert_price_high_stockalert_price_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='alert_type',
            field=models.CharField(choices=[('above', 'Price Rises Above'), ('below', 'Price Falls Below'), ('between', 'Price In Between Range')], default='above', max_length=10),
        ),
    ]
