# Generated by Django 5.2 on 2026-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stockalert_notes_alter_stockalert_alert_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockalert',
            name='target_price',
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
